version: '2'

services:
  # portainer:
  #   image: portainer/portainer
  #   ports:
  #     - "9000:9001"
  #   command: -H unix:///var/run/docker.sock
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

  api:
    container_name: static-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    working_dir: /usr/app
    volumes:
        - .:/usr/app
    command: 'python manage.py'

  postgres:
    container_name: static_db
    working_dir: /usr/app
    volumes:
        - postgres_data:/var/lib/postgresql/data
    image: 'postgres:9.6.10-alpine'
    environment:
      POSTGRES_USER: static
      POSTGRES_PASSWORD: static
      POSTGRES_DB : static_service
      PG_VERSION: '9.6.10-alpine'
    ports:
        - "5432:5432"

  redis:
      container_name: static-redis
      image: 'bitnami/redis:latest'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      ports:
        - '6379:6379'
      volumes:
        - redis_data:/bitnami

volumes:
  postgres_data:
  redis_data:
